Add configuration for the monitor health check.
vistaprint/terraform-newrelic-monitoring pull request #7
Opened 2019-10-29 10:46 UTC by ivansg

Add configuration for themonitor health check. 
Add defaults to variables documentation.
Use the fully qualified app name for all the resources

2019-10-29 15:35 UTC, betabandido requested changes

2019-10-29 16:27 UTC, ivansg commented on variables.tf
> +  description = "True if creating a custom dashboard is desired; false otherwise. Default: false"
Yes, you're right. I din't realise that the optional fields already show the default value in the Terraform registry.

2019-10-29 16:31 UTC, ivansg commented on alerts.tf
> +  name = "${var.newrelic_fully_qualified_app_name} Non Urgent"
Right, and I think it's simpler to keep the convention of the fully qualified app name than to come up with another convention. 
I removed the **newrelic_app_name** variable from the module.

2019-10-29 17:08 UTC, betabandido requested changes
Some minor changes (formatting).

2019-10-30 09:09 UTC, ivansg commented on README.md
> +  synthetics_monitor_health_endpoint_url           = "https://your-service-url.com"
Done

2019-10-30 09:15 UTC, ivansg commented on alerts.tf
> +  bypass_head_request = var.synthetics_monitor_bypass_head_request
Thank you, I was not aware of the Format Document action

2019-10-30 09:15 UTC, ivansg commented on test/test.tf
> +
Done

2019-10-30 11:17 UTC, betabandido approved these changes

2026-01-22 16:29 UTC, closed without merging